apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multicloud-integrations-role
rules:
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
      - delete
      - deletecollection
    apiGroups:
      - addon.open-cluster-management.io
      - agent.open-cluster-management.io
      - apps.open-cluster-management.io
      - cluster.open-cluster-management.io
      - operator.open-cluster-management.io
      - work.open-cluster-management.io
      - view.open-cluster-management.io
      - authentication.open-cluster-management.io
    resources:
      - channels
      - channels/status
      - channels/finalizers
      - deployables
      - deployables/status
      - gitopsclusters
      - gitopsclusters/status
      - helmreleases
      - helmreleases/status
      - klusterletaddonconfigs
      - manifestworks
      - manifestworks/status
      - managedclusters
      - managedclusterviews
      - managedclusterviews/status
      - managedclusteraddons
      - managedserviceaccounts
      - multiclusterhubs
      - placements
      - placements/status
      - placement/finalizers
      - placementbindings
      - placementbindings/finalizers
      - placementdecisions
      - placementdecisions/status
      - placementdecisions/finalizers
      - placementrules
      - placementrules/status
      - placementrules/finalizers
      - subscriptions
      - subscriptions/finalizers
      - subscriptions/status
      - subscriptionstatuses
      - subscriptionreports
      - multiclusterapplicationsetreports
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - app.k8s.io
      - argoproj.io
    resources:
      - applications
      - applications/status
      - applicationsets
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
    apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - events
      - secrets
      - serviceaccounts
      - services
      - services/proxy
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
      - clusterrolebindings
      - clusterroles
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - admissionregistration.k8s.io
      - certificates.k8s.io
      - coordination.k8s.io
      - apiextensions.k8s.io
    resources:
      - certificatesigningrequests
      - customresourcedefinitions
      - leases
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - hive.openshift.io
      - multicluster.openshift.io
    resources:
      - clusterimagesets
      - multiclusterengines
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
